import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable, of } from 'rxjs';
import { Product } from '../models/product.model';

@Injectable({ providedIn: 'root' })
export class ProductService {
  // Productos estáticos iniciales (Estos productos deben ser reemplazados por datos de la API)
  private staticProducts: Product[] = [
    {
      id: 1,
      nombre: 'Jarrón de Cerámica Artesanal',
      precio: 45,
      descripcion:
        'Jarrón hecho a mano con diseños únicos, perfecto para decoración.',
      imagen: 'https://picsum.photos/id/237/300/300', // Imagen genérica de cerámica
      categoria: 'Cerámica',
      stock: 10,
      ubicacion: 'Cusco, Perú',
      especificaciones: 'Altura: 30cm, Material: Cerámica, Pintura no tóxica',
    },
    {
      id: 2,
      nombre: 'Plato de Cerámica Decorativo',
      precio: 30,
      descripcion: 'Plato pintado a mano con detalles tradicionales.',
      imagen: 'https://picsum.photos/id/238/300/300',
      categoria: 'Cerámica',
      stock: 15,
      ubicacion: 'Arequipa, Perú',
      especificaciones: 'Diámetro: 25cm, Material: Cerámica, Pintura resistente al agua',
    },
    {
      id: 3,
      nombre: 'Taza de Cerámica Rústica',
      precio: 20,
      descripcion: 'Taza hecha a mano con acabado rústico y esmalte natural.',
      imagen: 'https://picsum.photos/id/239/300/300',
      categoria: 'Cerámica',
      stock: 20,
      ubicacion: 'Quito, Ecuador',
      especificaciones: 'Capacidad: 300ml, Material: Cerámica, Apto para microondas',
    },
    {
      id: 4,
      nombre: 'Maceta de Cerámica Minimalista',
      precio: 25,
      descripcion: 'Maceta de diseño simple, ideal para interiores modernos.',
      imagen: 'https://picsum.photos/id/240/300/300',
      categoria: 'Cerámica',
      stock: 18,
      ubicacion: 'Mendoza, Argentina',
      especificaciones: 'Altura: 15cm, Material: Cerámica, Drenaje incluido',
    },
    {
      id: 5,
      nombre: 'Set de Cuencos de Cerámica',
      precio: 50,
      descripcion: 'Set de 3 cuencos con texturas y colores únicos.',
      imagen: 'https://picsum.photos/id/241/300/300',
      categoria: 'Cerámica',
      stock: 12,
      ubicacion: 'Bogotá, Colombia',
      especificaciones: 'Diámetro: 12cm, Material: Cerámica, Apto para lavavajillas',
    },
    {
      id: 6,
      nombre: 'Jarra de Cerámica Esmaltada',
      precio: 40,
      descripcion: 'Jarra de cerámica con esmalte brillante y asa ergonómica.',
      imagen: 'https://picsum.photos/id/242/300/300',
      categoria: 'Cerámica',
      stock: 10,
      ubicacion: 'Lima, Perú',
      especificaciones: 'Capacidad: 1L, Material: Cerámica, Resistente a altas temperaturas',
    },
    {
      id: 7,
      nombre: 'Porta Velas de Cerámica Tallado',
      precio: 22,
      descripcion: 'Porta velas artesanal con detalles calados.',
      imagen: 'https://picsum.photos/id/243/300/300',
      categoria: 'Cerámica',
      stock: 14,
      ubicacion: 'Córdoba, Argentina',
      especificaciones: 'Altura: 10cm, Material: Cerámica, Diseño artesanal',
    },
    {
      id: 8,
      nombre: 'Plato de Servir en Cerámica',
      precio: 35,
      descripcion: 'Plato grande ideal para servir comidas con estilo.',
      imagen: 'https://picsum.photos/id/244/300/300',
      categoria: 'Cerámica',
      stock: 8,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Diámetro: 30cm, Material: Cerámica, Apto para horno',
    },
    {
      id: 9,
      nombre: 'Escultura Decorativa en Cerámica',
      precio: 55,
      descripcion: 'Pieza única de cerámica ideal para decoración elegante.',
      imagen: 'https://picsum.photos/id/245/300/300',
      categoria: 'Cerámica',
      stock: 5,
      ubicacion: 'Barcelona, España',
      especificaciones: 'Altura: 25cm, Material: Cerámica, Hecho a mano',
    },
    {
      id: 10,
      nombre: 'Set de Platos Hondos de Cerámica',
      precio: 45,
      descripcion: 'Conjunto de 4 platos hondos con acabados rústicos.',
      imagen: 'https://picsum.photos/id/246/300/300',
      categoria: 'Cerámica',
      stock: 10,
      ubicacion: 'Montevideo, Uruguay',
      especificaciones: 'Diámetro: 20cm, Material: Cerámica, Apto para lavavajillas',
    },
    {
      id: 11,
      nombre: 'Tetera de Cerámica Japonesa',
      precio: 60,
      descripcion: 'Tetera con diseño tradicional japonés, ideal para té.',
      imagen: 'https://picsum.photos/id/247/300/300',
      categoria: 'Cerámica',
      stock: 7,
      ubicacion: 'Tokio, Japón',
      especificaciones: 'Capacidad: 500ml, Material: Cerámica, Incluye filtro de té',
    },
    {
      id: 12,
      nombre: 'Caja Organizadora de Madera',
      precio: 35,
      descripcion: 'Caja artesanal ideal para almacenar objetos pequeños.',
      imagen: 'https://picsum.photos/id/248/300/300',
      categoria: 'Madera',
      stock: 12,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Dimensiones: 30x20x15cm, Material: Madera de roble, Hecho a mano',
    },
    {
      id: 13,
      nombre: 'Tabla para Picadas de Madera',
      precio: 28,
      descripcion: 'Tabla rústica para servir picadas y aperitivos.',
      imagen: 'https://picsum.photos/id/249/300/300',
      categoria: 'Madera',
      stock: 20,
      ubicacion: 'Rosario, Argentina',
      especificaciones: 'Dimensiones: 40x25cm, Material: Madera de acacia, Tratamiento antibacteriano',
    },
    {
      id: 14,
      nombre: 'Reloj de Pared de Madera',
      precio: 50,
      descripcion: 'Reloj artesanal con números tallados en madera.',
      imagen: 'https://picsum.photos/id/250/300/300',
      categoria: 'Madera',
      stock: 8,
      ubicacion: 'Madrid, España',
      especificaciones: 'Diámetro: 30cm, Material: Madera de nogal, Mecanismo silencioso',
    },
    {
      id: 15,
      nombre: 'Set de Cubiertos de Madera',
      precio: 22,
      descripcion: 'Cubiertos ecológicos hechos de madera de bambú.',
      imagen: 'https://picsum.photos/id/251/300/300',
      categoria: 'Madera',
      stock: 25,
      ubicacion: 'Lima, Perú',
      especificaciones: 'Incluye 1 cuchillo, 1 tenedor, 1 cuchara, Material: Bambú, Reutilizable',
    },
    {
      id: 16,
      nombre: 'Porta Llaves de Madera',
      precio: 18,
      descripcion: 'Organizador de llaves con ganchos metálicos.',
      imagen: 'https://picsum.photos/id/252/300/300',
      categoria: 'Madera',
      stock: 15,
      ubicacion: 'Bogotá, Colombia',
      especificaciones: 'Dimensiones: 25x15cm, Material: Madera de pino, 5 ganchos metálicos',
    },
    {
      id: 17,
      nombre: 'Estante Flotante de Madera',
      precio: 45,
      descripcion: 'Estante de pared ideal para libros y decoración.',
      imagen: 'https://picsum.photos/id/253/300/300',
      categoria: 'Madera',
      stock: 10,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Dimensiones: 60x20cm, Material: Madera de cedro, Instalación sencilla',
    },
    {
      id: 18,
      nombre: 'Lámpara de Madera Artesanal',
      precio: 65,
      descripcion: 'Lámpara de mesa con base de madera tallada.',
      imagen: 'https://picsum.photos/id/254/300/300',
      categoria: 'Madera',
      stock: 6,
      ubicacion: 'Montevideo, Uruguay',
      especificaciones: 'Altura: 40cm, Material: Madera de roble, Cableado con interruptor',
    },
    {
      id: 19,
      nombre: 'Bandeja de Madera Rústica',
      precio: 30,
      descripcion: 'Bandeja con asas metálicas para servir con estilo.',
      imagen: 'https://picsum.photos/id/255/300/300',
      categoria: 'Madera',
      stock: 14,
      ubicacion: 'Cusco, Perú',
      especificaciones: 'Dimensiones: 35x25cm, Material: Madera de teka, Barniz protector',
    },
    {
      id: 20,
      nombre: 'Marco de Fotos de Madera',
      precio: 25,
      descripcion: 'Marco rústico ideal para fotos familiares.',
      imagen: 'https://picsum.photos/id/256/300/300',
      categoria: 'Madera',
      stock: 18,
      ubicacion: 'Quito, Ecuador',
      especificaciones: 'Tamaño: 20x25cm, Material: Madera de abeto, Vidrio frontal',
    },
    {
      id: 21,
      nombre: 'Escultura de Madera Tallada',
      precio: 80,
      descripcion: 'Pieza decorativa única tallada a mano.',
      imagen: 'https://picsum.photos/id/257/300/300',
      categoria: 'Madera',
      stock: 3,
      ubicacion: 'Córdoba, Argentina',
      especificaciones: 'Altura: 35cm, Material: Madera de nogal, Hecho a mano',
    },
    {
      id: 22,
      nombre: 'Pintura al Óleo Abstracta',
      precio: 120,
      descripcion: 'Obra única pintada a mano con técnica al óleo.',
      imagen: 'https://picsum.photos/id/258/300/300',
      categoria: 'Arte',
      stock: 2,
      ubicacion: 'Barcelona, España',
      especificaciones: 'Dimensiones: 70x50cm, Técnica: Óleo sobre lienzo, Enmarcado',
    },
    {
      id: 23,
      nombre: 'Escultura Moderna en Resina',
      precio: 150,
      descripcion: 'Escultura de diseño abstracto ideal para decoración contemporánea.',
      imagen: 'https://picsum.photos/id/259/300/300',
      categoria: 'Arte',
      stock: 3,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Altura: 40cm, Material: Resina, Acabado brillante',
    },
    {
      id: 24,
      nombre: 'Cuadro en Acuarela Paisajístico',
      precio: 90,
      descripcion: 'Pintura en acuarela de un paisaje natural.',
      imagen: 'https://picsum.photos/id/260/300/300',
      categoria: 'Arte',
      stock: 5,
      ubicacion: 'Lima, Perú',
      especificaciones: 'Dimensiones: 50x40cm, Técnica: Acuarela sobre papel, Enmarcado en madera',
    },
    {
      id: 25,
      nombre: 'Máscara Tallada a Mano',
      precio: 75,
      descripcion: 'Máscara artesanal con detalles tribales únicos.',
      imagen: 'https://picsum.photos/id/261/300/300',
      categoria: 'Arte',
      stock: 7,
      ubicacion: 'Cusco, Perú',
      especificaciones: 'Dimensiones: 30x20cm, Material: Madera tallada, Pintura ecológica',
    },
    {
      id: 26,
      nombre: 'Taller de Pintura en Vivo',
      precio: 200,
      descripcion: 'Experiencia artística con un artista profesional.',
      imagen: 'https://picsum.photos/id/262/300/300',
      categoria: 'Arte',
      stock: 10,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Duración: 3 horas, Incluye materiales, Técnica a elección',
    },
    {
      id: 27,
      nombre: 'Anillo de Plata 925 con Ópalo',
      precio: 85,
      descripcion: 'Anillo artesanal con piedra de ópalo engarzada.',
      imagen: 'https://picsum.photos/id/263/300/300',
      categoria: 'Joyería',
      stock: 10,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Material: Plata 925, Piedra: Ópalo, Ajustable',
    },
    {
      id: 28,
      nombre: 'Collar de Cuarzo Rosa',
      precio: 65,
      descripcion: 'Collar hecho a mano con dije de cuarzo rosa natural.',
      imagen: 'https://picsum.photos/id/264/300/300',
      categoria: 'Joyería',
      stock: 15,
      ubicacion: 'Lima, Perú',
      especificaciones: 'Largo: 45cm, Material: Acero inoxidable y cuarzo rosa, Cierre ajustable',
    },
    {
      id: 29,
      nombre: 'Pulsera de Piedras Naturales',
      precio: 40,
      descripcion: 'Pulsera elástica con piedras volcánicas y jaspe.',
      imagen: 'https://picsum.photos/id/265/300/300',
      categoria: 'Joyería',
      stock: 20,
      ubicacion: 'Bogotá, Colombia',
      especificaciones: 'Material: Piedras naturales, Tamaño ajustable, Diseño artesanal',
    },
    {
      id: 30,
      nombre: 'Aros de Plata con Zafiros',
      precio: 120,
      descripcion: 'Aros elegantes con incrustaciones de zafiro azul.',
      imagen: 'https://picsum.photos/id/266/300/300',
      categoria: 'Joyería',
      stock: 8,
      ubicacion: 'Madrid, España',
      especificaciones: 'Material: Plata 925, Piedras: Zafiros, Cierre de presión',
    },
    {
      id: 31,
      nombre: 'Reloj de Madera y Acero',
      precio: 180,
      descripcion: 'Reloj exclusivo con correa de madera y acero inoxidable.',
      imagen: 'https://picsum.photos/id/267/300/300',
      categoria: 'Joyería',
      stock: 5,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Material: Madera y acero inoxidable, Movimiento: Cuarzo japonés, Resistente al agua',
    },
    {
      id: 32,
      nombre: 'Broche Vintage de Oro Rosa',
      precio: 95,
      descripcion: 'Broche clásico con diseño floral en oro rosa.',
      imagen: 'https://picsum.photos/id/268/300/300',
      categoria: 'Joyería',
      stock: 12,
      ubicacion: 'Barcelona, España',
      especificaciones: 'Material: Oro rosa bañado, Cierre seguro, Diseño vintage',
    },
    {
      id: 33,
      nombre: 'Tobillera con Dijes de Estrella',
      precio: 35,
      descripcion: 'Tobillera minimalista con pequeños dijes de estrella.',
      imagen: 'https://picsum.photos/id/269/300/300',
      categoria: 'Joyería',
      stock: 18,
      ubicacion: 'Montevideo, Uruguay',
      especificaciones: 'Material: Plata bañada en oro, Largo: 22cm, Cierre ajustable',
    },
    {
      id: 34,
      nombre: 'Jabón Artesanal de Lavanda',
      precio: 25,
      descripcion: 'Jabón hecho a mano con aceite esencial de lavanda.',
      imagen: 'https://picsum.photos/id/270/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 15,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Ingredientes: Aceites vegetales, lavanda, sin parabenos, 100g',
    },
    {
      id: 35,
      nombre: 'Crema Hidratante de Aloe Vera',
      precio: 40,
      descripcion: 'Crema ligera con extracto puro de aloe vera para hidratación profunda.',
      imagen: 'https://picsum.photos/id/271/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 12,
      ubicacion: 'Lima, Perú',
      especificaciones: 'Ingredientes: Aloe vera, manteca de karité, 200ml, sin fragancias artificiales',
    },
    {
      id: 36,
      nombre: 'Bálsamo Labial de Miel y Cacao',
      precio: 18,
      descripcion: 'Bálsamo labial nutritivo con ingredientes naturales.',
      imagen: 'https://picsum.photos/id/272/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 20,
      ubicacion: 'Bogotá, Colombia',
      especificaciones: 'Ingredientes: Cera de abeja, miel, cacao, 10g, sin petrolatos',
    },
    {
      id: 37,
      nombre: 'Aceite Corporal de Almendras',
      precio: 55,
      descripcion: 'Aceite puro de almendras para hidratación y masajes.',
      imagen: 'https://picsum.photos/id/273/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 10,
      ubicacion: 'Madrid, España',
      especificaciones: 'Ingredientes: Aceite de almendras 100% puro, 250ml, prensado en frío',
    },
    {
      id: 38,
      nombre: 'Shampoo Sólido de Romero y Menta',
      precio: 30,
      descripcion: 'Shampoo sólido sin sulfatos, ideal para fortalecer el cabello.',
      imagen: 'https://picsum.photos/id/274/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 18,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Ingredientes: Romero, menta, aceite de coco, 90g, vegano',
    },
    {
      id: 39,
      nombre: 'Exfoliante Facial de Café',
      precio: 38,
      descripcion: 'Exfoliante natural con granos de café reciclados.',
      imagen: 'https://picsum.photos/id/275/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 14,
      ubicacion: 'Barcelona, España',
      especificaciones: 'Ingredientes: Café molido, aceite de coco, azúcar, 150g, libre de químicos',
    },
    {
      id: 40,
      nombre: 'Desodorante Natural en Barra',
      precio: 28,
      descripcion: 'Desodorante sin aluminio con aroma fresco a cítricos.',
      imagen: 'https://picsum.photos/id/276/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 16,
      ubicacion: 'Montevideo, Uruguay',
      especificaciones: 'Ingredientes: Bicarbonato, aceites esenciales, cera de abeja, 50g',
    },
    {
      id: 41,
      nombre: 'Mascarilla Capilar de Karité',
      precio: 60,
      descripcion: 'Mascarilla nutritiva para el cabello seco y dañado.',
      imagen: 'https://picsum.photos/id/277/300/300',
      categoria: 'Cosméticos Naturales',
      stock: 8,
      ubicacion: 'Quito, Ecuador',
      especificaciones: 'Ingredientes: Manteca de karité, aceite de argán, 300ml, sin siliconas',
    },
    {
      id: 42,
      nombre: 'Almohadón de Lino Bordado',
      precio: 50,
      descripcion: 'Cojín decorativo con diseño artesanal bordado a mano.',
      imagen: 'https://picsum.photos/id/278/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 12,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Material: Lino 100%, Relleno: Algodón, Dimensiones: 45x45cm',
    },
    {
      id: 43,
      nombre: 'Lámpara de Mesa de Madera',
      precio: 95,
      descripcion: 'Lámpara con base de madera reciclada y pantalla de lino.',
      imagen: 'https://picsum.photos/id/279/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 8,
      ubicacion: 'Lima, Perú',
      especificaciones: 'Altura: 35cm, Material: Madera y lino, Bombilla LED incluida',
    },
    {
      id: 44,
      nombre: 'Porta Velas de Cerámica',
      precio: 30,
      descripcion: 'Soporte para velas con detalles tallados a mano.',
      imagen: 'https://picsum.photos/id/280/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 15,
      ubicacion: 'Bogotá, Colombia',
      especificaciones: 'Material: Cerámica, Diámetro: 12cm, Diseño artesanal',
    },
    {
      id: 45,
      nombre: 'Reloj de Pared Minimalista',
      precio: 110,
      descripcion: 'Reloj decorativo de madera con diseño moderno.',
      imagen: 'https://picsum.photos/id/281/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 5,
      ubicacion: 'Madrid, España',
      especificaciones: 'Diámetro: 40cm, Material: Madera, Movimiento silencioso',
    },
    {
      id: 46,
      nombre: 'Set de Posavasos de Bambú',
      precio: 22,
      descripcion: 'Juego de 6 posavasos ecológicos hechos de bambú.',
      imagen: 'https://picsum.photos/id/282/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 20,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Material: Bambú, Diámetro: 10cm, Incluye soporte',
    },
    {
      id: 47,
      nombre: 'Espejo Decorativo con Marco de Ratán',
      precio: 85,
      descripcion: 'Espejo redondo con marco artesanal de ratán tejido.',
      imagen: 'https://picsum.photos/id/283/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 7,
      ubicacion: 'Barcelona, España',
      especificaciones: 'Diámetro: 50cm, Material: Ratán natural, Listo para colgar',
    },
    {
      id: 48,
      nombre: 'Cesta Organizadora de Yute',
      precio: 40,
      descripcion: 'Cesta tejida a mano, ideal para almacenamiento.',
      imagen: 'https://picsum.photos/id/284/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 10,
      ubicacion: 'Montevideo, Uruguay',
      especificaciones: 'Material: Yute natural, Dimensiones: 30x30cm, Reforzada con asas',
    },
    {
      id: 49,
      nombre: 'Tapiz Boho en Macramé',
      precio: 70,
      descripcion: 'Decoración de pared tejida con hilos de algodón.',
      imagen: 'https://picsum.photos/id/285/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 6,
      ubicacion: 'Quito, Ecuador',
      especificaciones: 'Material: Algodón, Dimensiones: 60x80cm, Hecho a mano',
    },
    {
      id: 50,
      nombre: 'Difusor de Aromas de Madera',
      precio: 55,
      descripcion: 'Difusor ultrasónico con luz LED y esencia de lavanda.',
      imagen: 'https://picsum.photos/id/286/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 9,
      ubicacion: 'Cusco, Perú',
      especificaciones: 'Capacidad: 200ml, Material: Madera y plástico, Incluye cable USB',
    },
    {
      id: 51,
      nombre: 'Estante Flotante de Roble',
      precio: 120,
      descripcion: 'Estante minimalista para libros y decoración.',
      imagen: 'https://picsum.photos/id/287/300/300',
      categoria: 'Accesorios para el Hogar',
      stock: 4,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Material: Madera de roble, Dimensiones: 80x20cm, Incluye kit de instalación',
    },
    {
      id: 52,
      nombre: 'Botella Reutilizable de Acero Inoxidable',
      precio: 45,
      descripcion: 'Botella térmica ecológica para mantener bebidas frías o calientes.',
      imagen: 'https://picsum.photos/id/288/300/300',
      categoria: 'Productos Ecológicos',
      stock: 15,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Capacidad: 750ml, Material: Acero inoxidable, Doble pared térmica',
    },
    {
      id: 53,
      nombre: 'Set de Cubiertos de Bambú',
      precio: 25,
      descripcion: 'Cubiertos ecológicos reutilizables con estuche de tela.',
      imagen: 'https://picsum.photos/id/289/300/300',
      categoria: 'Productos Ecológicos',
      stock: 20,
      ubicacion: 'Lima, Perú',
      especificaciones: 'Material: Bambú, Incluye cuchillo, tenedor, cuchara y sorbete con limpiador',
    },
    {
      id: 54,
      nombre: 'Bolsas de Tela para Compras',
      precio: 30,
      descripcion: 'Juego de 3 bolsas reutilizables de algodón orgánico.',
      imagen: 'https://picsum.photos/id/290/300/300',
      categoria: 'Productos Ecológicos',
      stock: 18,
      ubicacion: 'Bogotá, Colombia',
      especificaciones: 'Material: Algodón 100%, Tamaño: 40x45cm, Lavables y resistentes',
    },
    {
      id: 55,
      nombre: 'Cepillo de Dientes de Bambú',
      precio: 12,
      descripcion: 'Cepillo biodegradable con cerdas de carbón activado.',
      imagen: 'https://picsum.photos/id/291/300/300',
      categoria: 'Productos Ecológicos',
      stock: 25,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Material: Bambú natural, Cerdas: Carbón activado, Biodegradable',
    },
    {
      id: 56,
      nombre: 'Miel Orgánica Pura',
      precio: 50,
      descripcion: 'Miel 100% pura cosechada de colmenas ecológicas.',
      imagen: 'https://picsum.photos/id/292/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 10,
      ubicacion: 'Mendoza, Argentina',
      especificaciones: 'Contenido: 500g, Sin aditivos, Producción artesanal',
    },
    {
      id: 57,
      nombre: 'Mermelada de Frutos Rojos',
      precio: 35,
      descripcion: 'Mermelada casera elaborada con frambuesas y arándanos.',
      imagen: 'https://picsum.photos/id/293/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 12,
      ubicacion: 'Valparaíso, Chile',
      especificaciones: 'Contenido: 300g, Sin conservantes, Ingredientes naturales',
    },
    {
      id: 58,
      nombre: 'Pan Integral con Semillas',
      precio: 20,
      descripcion: 'Pan artesanal hecho con harina integral y semillas seleccionadas.',
      imagen: 'https://picsum.photos/id/294/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 15,
      ubicacion: 'Quito, Ecuador',
      especificaciones: 'Peso: 500g, Ingredientes: Harina integral, chía, lino, sésamo',
    },
    {
      id: 59,
      nombre: 'Chocolate Artesanal 70% Cacao',
      precio: 45,
      descripcion: 'Chocolate negro elaborado con granos de cacao ecuatoriano.',
      imagen: 'https://picsum.photos/id/295/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 20,
      ubicacion: 'Guayaquil, Ecuador',
      especificaciones: 'Peso: 100g, Ingredientes: Cacao, azúcar de caña, sin conservantes',
    },
    {
      id: 60,
      nombre: 'Queso de Cabra Curado',
      precio: 80,
      descripcion: 'Queso artesanal madurado con un sabor intenso y cremoso.',
      imagen: 'https://picsum.photos/id/296/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 8,
      ubicacion: 'Córdoba, Argentina',
      especificaciones: 'Peso: 400g, Elaborado con leche de cabra, maduración 6 meses',
    },
    {
      id: 61,
      nombre: 'Aceite de Oliva Extra Virgen',
      precio: 65,
      descripcion: 'Aceite prensado en frío con un sabor intenso y afrutado.',
      imagen: 'https://picsum.photos/id/297/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 10,
      ubicacion: 'Mendoza, Argentina',
      especificaciones: 'Contenido: 500ml, Origen: Aceitunas seleccionadas, Producción artesanal',
    },
    {
      id: 62,
      nombre: 'Dulce de Leche Casero',
      precio: 30,
      descripcion: 'Dulce de leche elaborado con leche fresca y azúcar.',
      imagen: 'https://picsum.photos/id/298/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 14,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Contenido: 400g, Sin conservantes, Método tradicional',
    },
    {
      id: 63,
      nombre: 'Té de Hierbas Andinas',
      precio: 25,
      descripcion: 'Infusión natural con mezcla de hierbas curativas de los Andes.',
      imagen: 'https://picsum.photos/id/299/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 18,
      ubicacion: 'Cusco, Perú',
      especificaciones: 'Peso: 100g, Ingredientes: Muña, coca, cedrón, producción orgánica',
    },
    {
      id: 64,
      nombre: 'Granola Casera con Frutas Secas',
      precio: 38,
      descripcion: 'Granola crujiente elaborada con avena, frutos secos y miel.',
      imagen: 'https://picsum.photos/id/300/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 12,
      ubicacion: 'Bogotá, Colombia',
      especificaciones: 'Peso: 500g, Ingredientes: Avena, almendras, miel, pasas, coco',
    },
    {
      id: 65,
      nombre: 'Mantequilla de Maní Natural',
      precio: 28,
      descripcion: 'Mantequilla de maní sin azúcar ni conservantes.',
      imagen: 'https://picsum.photos/id/301/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 20,
      ubicacion: 'Santiago, Chile',
      especificaciones: 'Peso: 300g, Ingredientes: Maní tostado, sin aceites añadidos',
    },
    {
      id: 66,
      nombre: 'Pasta de Almendras Artesanal',
      precio: 48,
      descripcion: 'Crema de almendras 100% natural, sin aditivos.',
      imagen: 'https://picsum.photos/id/302/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 9,
      ubicacion: 'Montevideo, Uruguay',
      especificaciones: 'Peso: 250g, Ingredientes: Almendras tostadas, sin conservantes',
    },
    {
      id: 67,
      nombre: 'Empanadas Salteñas Caseras',
      precio: 40,
      descripcion: 'Empanadas tradicionales con relleno de carne y especias.',
      imagen: 'https://picsum.photos/id/303/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 16,
      ubicacion: 'Salta, Argentina',
      especificaciones: 'Porción: 6 unidades, Masa artesanal, Cocción al horno',
    },
    {
      id: 68,
      nombre: 'Dátiles Rellenos con Nueces',
      precio: 32,
      descripcion: 'Dátiles orgánicos rellenos con nueces y miel.',
      imagen: 'https://picsum.photos/id/304/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 14,
      ubicacion: 'Marrakech, Marruecos',
      especificaciones: 'Peso: 250g, Ingredientes: Dátiles, nueces, miel natural',
    },
    {
      id: 69,
      nombre: 'Sal de Maras con Hierbas',
      precio: 22,
      descripcion: 'Sal natural de Maras con mezcla de hierbas aromáticas.',
      imagen: 'https://picsum.photos/id/305/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 18,
      ubicacion: 'Cusco, Perú',
      especificaciones: 'Peso: 250g, Ingredientes: Sal rosada, orégano, tomillo, romero',
    },
    {
      id: 70,
      nombre: 'Yerba Mate Orgánica',
      precio: 42,
      descripcion: 'Yerba mate sin agroquímicos, cosechada de manera artesanal.',
      imagen: 'https://picsum.photos/id/306/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 15,
      ubicacion: 'Misiones, Argentina',
      especificaciones: 'Peso: 1kg, Libre de químicos, Secado natural',
    },
    {
      id: 71,
      nombre: 'Chutney de Mango Casero',
      precio: 36,
      descripcion: 'Salsa agridulce artesanal hecha con mango fresco y especias.',
      imagen: 'https://picsum.photos/id/307/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 11,
      ubicacion: 'Cartagena, Colombia',
      especificaciones: 'Contenido: 250g, Ingredientes: Mango, vinagre, azúcar de caña',
    },
    {
      id: 72,
      nombre: 'Pan de Masa Madre',
      precio: 55,
      descripcion: 'Pan rústico elaborado con fermentación natural.',
      imagen: 'https://picsum.photos/id/308/300/300',
      categoria: 'Alimentos Artesanales',
      stock: 10,
      ubicacion: 'Buenos Aires, Argentina',
      especificaciones: 'Peso: 750g, Harina integral, sin levaduras industriales',
    },
  ];

  // Fuente de datos para productos dinámicos (Esto debe ser reemplazado por los productos de la API)
  private dynamicProductsSource = new BehaviorSubject<Product[]>([]);

  // Observable para exponer los productos dinámicos (se mantendrá para productos obtenidos de la API)
  public dynamicProductsPublic$: Observable<Product[]> =
    this.dynamicProductsSource.asObservable();

  // Combina productos estáticos + dinámicos
  // En el futuro, esta función debería fusionar los productos estáticos con los que provengan de la API(Aunque los productos estaticos ya no serán necesarios).
  getAllProducts(): Product[] {
    return [...this.staticProducts, ...this.dynamicProductsSource.value]; // Accede al value para obtener los productos dinámicos
  }

  // Añade un nuevo producto con ID único
  // Aca se tiene cambiar la lógica para enviar el producto a la API en vez de solo agregarlo localmente.
  addProduct(newProduct: Omit<Product, 'id'>): void {
    const newId = this.generateNewId();
    console.log('Nuevo producto recibido:', newProduct);
    const productWithId: Product = {
      ...newProduct,
      id: newId,
      vendedorId: newProduct.vendedorId,
    };

    const currentDynamicProducts = this.dynamicProductsSource.value;
    this.dynamicProductsSource.next([...currentDynamicProducts, productWithId]);
  }

  // Genera un ID único evitando colisiones con los productos estáticos (esto es local, pero deberías obtener un ID de la API más adelante)
  private generateNewId(): number {
    const maxStaticId = Math.max(...this.staticProducts.map((p) => p.id));
    //Se usa dynamicProductsSource.value para calcular el ID, pero en la API se deberia permitir gestione este ID
    return maxStaticId + this.dynamicProductsSource.value.length + 1;
  }

  private normalizeText(text: string): string {
    return text
      .normalize('NFD') // Separa caracteres y diacríticos (ej: 'ç' -> 'c' + '̧')
      .replace(/[\u0300-\u036f]/g, '') // Elimina diacríticos
      .toLowerCase();
  }

  // Método de búsqueda
  searchProducts(query: string): Observable<Product[]> {
    const normalizedQuery = this.normalizeText(query);
    const allProducts = this.getAllProducts();

    const filtered = allProducts.filter((product) => {
      const nombre = this.normalizeText(product.nombre || '');
      const descripcion = this.normalizeText(product.descripcion || '');
      const categoria = this.normalizeText(product.categoria || '');

      return (
        nombre.includes(normalizedQuery) ||
        descripcion.includes(normalizedQuery) ||
        categoria.includes(normalizedQuery)
      );
    });

    return of(filtered);
  }
  getProductById(id: number): Product | undefined {
    const allProducts = this.getAllProducts();
    return allProducts.find((product) => product.id === id);
  }
}
